openapi: 3.0.3
info:
  title: Users Domain
  version: 1.0.0
  description: Operations related to users.

paths:
  /users:
    get:
      summary: List all users
      tags:
        - Users
      parameters:
        - $ref: '../../shared/parameters/Pagination.yaml'
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './schemas/User.yaml'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '../../shared/schemas/Error.yaml'
  /users/{userId}:
    $ref: './paths/get_user.yaml'

components:
  schemas:
    User:
      $ref: './schemas/User.yaml'
