# Generated by Django 6.0.2 on 2026-02-16 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="役職名")),
                ("rank", models.IntegerField(default=0, verbose_name="ランク")),
            ],
            options={
                "verbose_name": "役職",
                "verbose_name_plural": "役職",
                "ordering": ["rank"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="部署名")),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="部署コード"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="hr.department",
                        verbose_name="親部署",
                    ),
                ),
            ],
            options={
                "verbose_name": "部署",
                "verbose_name_plural": "部署",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="名")),
                ("last_name", models.CharField(max_length=50, verbose_name="姓")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="メールアドレス"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="電話番号"
                    ),
                ),
                ("hire_date", models.DateField(verbose_name="入社日")),
                ("is_active", models.BooleanField(default=True, verbose_name="在籍中")),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr.department",
                        verbose_name="部署",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr.position",
                        verbose_name="役職",
                    ),
                ),
            ],
            options={
                "verbose_name": "従業員",
                "verbose_name_plural": "従業員",
            },
        ),
    ]
