# Generated by Django 6.0.2 on 2026-02-16 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=0, verbose_name="在庫数")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="保管場所"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock",
                        to="sales.product",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "在庫",
                "verbose_name_plural": "在庫",
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("in", "入荷 (+)"),
                            ("out", "出荷 (-)"),
                            ("return", "返品受入 (+)"),
                            ("waste", "廃棄 (-)"),
                            ("adjust_in", "調整増 (+)"),
                            ("adjust_out", "調整減 (-)"),
                        ],
                        max_length=20,
                        verbose_name="移動タイプ",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="数量")),
                ("date", models.DateTimeField(auto_now_add=True, verbose_name="日時")),
                ("note", models.TextField(blank=True, null=True, verbose_name="備考")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="sales.product",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "入出庫履歴",
                "verbose_name_plural": "入出庫履歴",
                "ordering": ["-date"],
            },
        ),
    ]
